# Keys are the 'Data.country' from the API
# Values are country name in Hebrew (from gov website html), and English translation
GOV_API_DATA_COUNTRY_TO_NAME = {
    "001": {"he": "אוגנדה", "en": "Uganda"},
    "002": {"he": "אוזבקיסטן", "en": "Uzbekistan"},
    "003": {"he": "אוסטריה", "en": "Austria"},
    "004": {"he": "אוסטרליה", "en": "Australia"},
    "005": {"he": "אוקראינה", "en": "Ukraine"},
    "006": {"he": "אורוגואי", "en": "Uruguay"},
    "007": {"he": "אזרביג'אן", "en": "Azerbaijan"},
    "008": {"he": "איחוד האמירויות הערביות", "en": "United Arab Emirates"},
    "009": {"he": "איטליה", "en": "Italy"},
    "010": {"he": "איי בהאמה", "en": "Bahamas"},
    "011": {"he": "איי מרשל", "en": "Marshall Islands"},
    "012": {"he": "איי סיישל", "en": "Seychelles"},
    "013": {"he": "איי שלמה", "en": "Solomon Islands"},
    "014": {"he": "אינדונזיה", "en": "Indonesia"},
    "015": {"he": "איסלנד", "en": "Iceland"},
    "016": {"he": "איראן", "en": "Iran"},
    "017": {"he": "אירלנד", "en": "Ireland"},
    "018": {"he": "אל סלבדור", "en": "El Salvador"},
    "019": {"he": "אלבניה", "en": "Albania"},
    "020": {"he": "אלג'יריה", "en": "Algeria"},
    "021": {"he": "אנגולה", "en": "Angola"},
    "022": {"he": "אנדורה", "en": "Andorra"},
    "023": {"he": "אנטיגואה וברבודה", "en": "Antigua and Barbuda"},
    "024": {"he": "אסטוניה", "en": "Estonia"},
    "025": {"he": "אפגניסטן", "en": "Afghanistan"},
    "026": {"he": "אקוואדור", "en": "Ecuador"},
    "027": {"he": "ארגנטינה", "en": "Argentina"},
    "028": {"he": "אריתריאה", "en": "Eritrea"},
    "029": {"he": "ארמניה", "en": "Armenia"},
    "030": {"he": "ארצות הברית", "en": "United States"},
    "031": {"he": "אתיופיה", "en": "Ethiopia"},
    "032": {"he": "בהוטן", "en": "Bhutan"},
    "033": {"he": "בולגריה", "en": "Bulgaria"},
    "034": {"he": "בוליביה", "en": "Bolivia"},
    "035": {"he": "בוסניה הרצגובינה", "en": "Bosnia and Herzegovina"},
    "036": {"he": "בוטסואנה", "en": "Botswana"},
    "037": {"he": "בורונדי", "en": "Burundi"},
    "038": {"he": "בורקינה פאסו", "en": "Burkina Faso"},
    "039": {"he": "בחריין", "en": "Bahrain"},
    "040": {"he": "בלארוס", "en": "Belarus"},
    "041": {"he": "בלגיה", "en": "Belgium"},
    "042": {"he": "בליז", "en": "Belize"},
    "043": {"he": "בנגלדש", "en": "Bangladesh"},
    "044": {"he": "בנין", "en": "Benin"},
    "045": {"he": "ברבדוס", "en": "Barbados"},
    "046": {"he": "ברוניי", "en": "Brunei"},
    "047": {"he": "ברזיל", "en": "Brazil"},
    "048": {"he": "בריטניה", "en": "United Kingdom"},
    "049": {"he": "גאבון", "en": "Gabon"},
    "050": {"he": "גאורגיה", "en": "Georgia"},
    "051": {"he": "גאנה", "en": "Ghana"},
    "052": {"he": "גווטמלה", "en": "Guatemala"},
    "053": {"he": "גויאנה", "en": "Guyana"},
    "054": {"he": "ג'יבוטי", "en": "Djibouti"},
    "055": {"he": "גינאה", "en": "Guinea"},
    "056": {"he": "גינאה המשוונית", "en": "Equatorial Guinea"},
    "057": {"he": "גינאה-ביסאו", "en": "Guinea-Bissau"},
    "058": {"he": "ג'מאיקה", "en": "Jamaica"},
    "059": {"he": "גמביה", "en": "The Gambia"},
    "060": {"he": "גרמניה", "en": "Germany"},
    "061": {"he": "גרנדה", "en": "Grenada"},
    "062": {"he": "דומיניקה", "en": "Dominica"},
    "063": {"he": "דנמרק", "en": "Denmark"},
    "064": {"he": "דרום אפריקה", "en": "South Africa"},
    "065": {"he": "דרום סודאן", "en": "South Sudan"},
    "066": {"he": "האיטי", "en": "Haiti"},
    "067": {"he": "האיים המלדיביים", "en": "Maldives"},
    "068": {"he": "הודו", "en": "India"},
    "069": {"he": "הולנד", "en": "Netherlands"},
    "070": {"he": "הונג קונג", "en": "Hong Kong"},
    "071": {"he": "הונגריה", "en": "Hungary"},
    "072": {"he": "הונדורס", "en": "Honduras"},
    "073": {"he": "הרפובליקה הדומיניקנית", "en": "Dominican Republic"},
    "074": {"he": "הרפובליקה המרכז אפריקנית", "en": "Central African Republic"},
    "075": {"he": "הרפובליקה של קונגו", "en": "Republic of the Congo"},
    "076": {"he": "וייטנאם", "en": "Vietnam"},
    "077": {"he": "וותיקן", "en": "Vatican City"},
    "078": {"he": "ונואטו", "en": "Vanuatu"},
    "079": {"he": "ונצואלה", "en": "Venezuela"},
    "080": {"he": "זימבבואה", "en": "Zimbabwe"},
    "081": {"he": "זמביה", "en": "Zambia"},
    "082": {"he": "חוף השנהב", "en": "Ivory Coast"},
    "083": {"he": "טג'יקיסטאן", "en": "Tajikistan"},
    "084": {"he": "טובאלו", "en": "Tuvalu"},
    "085": {"he": "טוגו", "en": "Togo"},
    "086": {"he": "טונגה", "en": "Tonga"},
    "087": {"he": "טייואן", "en": "Taiwan"},
    "088": {"he": "טנזניה", "en": "Tanzania"},
    "089": {"he": "טרינידד וטובגו", "en": "Trinidad and Tobago"},
    "090": {"he": "יוון", "en": "Greece"},
    "091": {"he": "יפן", "en": "Japan"},
    "092": {"he": "ירדן", "en": "Jordan"},
    "093": {"he": "כווית", "en": "Kuwait"},
    "094": {"he": "לאוס", "en": "Laos"},
    "095": {"he": "לבנון", "en": "Lebanon"},
    "096": {"he": "לוב", "en": "Libya"},
    "097": {"he": "לוקסמבורג", "en": "Luxembourg"},
    "098": {"he": "לטביה", "en": "Latvia"},
    "099": {"he": "ליבריה", "en": "Liberia"},
    "100": {"he": "ליטא", "en": "Lithuania"},
    "101": {"he": "ליכטנשטיין", "en": "Liechtenstein"},
    "102": {"he": "לסוטו", "en": "Lesotho"},
    "103": {"he": "מאוריטניה", "en": "Mauritania"},
    "104": {"he": "מאוריציוס", "en": "Mauritius"},
    "105": {"he": "מאלי", "en": "Mali"},
    "106": {"he": "מדגסקר", "en": "Madagascar"},
    "107": {"he": "מוזמביק", "en": "Mozambique"},
    "108": {"he": "מולדובה", "en": "Moldova"},
    "109": {"he": "מונגוליה", "en": "Mongolia"},
    "110": {"he": "מונטנגרו", "en": "Montenegro"},
    "111": {"he": "מונקו", "en": "Monaco"},
    "112": {"he": "מזרח טימור (הרפובליקה הדמוקרטית)", "en": "East Timor"},
    "113": {"he": "מיאנמר", "en": "Myanmar"},
    "114": {"he": "מיקרונזיה", "en": "Micronesia"},
    "115": {"he": "מלאווי", "en": "Malawi"},
    "116": {"he": "מלזיה", "en": "Malaysia"},
    "117": {"he": "מלטה", "en": "Malta"},
    "118": {"he": "מצרים", "en": "Egypt"},
    "119": {"he": "מקסיקו", "en": "Mexico"},
    "120": {"he": "מרוקו", "en": "Morocco"},
    "121": {"he": "נאורו", "en": "Nauru"},
    "123": {"he": "נורווגיה", "en": "Norway"},
    "124": {"he": "ניגריה", "en": "Nigeria"},
    "125": {"he": "ניו זילנד", "en": "New Zealand"},
    "126": {"he": "ניז'ר", "en": "Niger"},
    "127": {"he": "ניקרגואה", "en": "Nicaragua"},
    "128": {"he": "נמיביה", "en": "Namibia"},
    "129": {"he": "נפאל", "en": "Nepal"},
    "130": {"he": "סאו טומה ופרינסיפ", "en": "São Tomé and Príncipe"},
    "131": {"he": "סודאן", "en": "Sudan"},
    "132": {"he": "סוואזילנד", "en": "Eswatini"},
    "133": {"he": "סומליה", "en": "Somalia"},
    "134": {"he": "סוריה", "en": "Syria"},
    "135": {"he": "סורינאם", "en": "Suriname"},
    "136": {"he": "סיירה ליאונה", "en": "Sierra Leone"},
    "137": {"he": "סין", "en": "China"},
    "138": {"he": "סינגפור", "en": "Singapore"},
    "139": {"he": "מצרים (חצי האי סיני)", "en": "Egypt (Sinai Peninsula)"},
    "140": {"he": "סלובניה", "en": "Slovenia"},
    "141": {"he": "סלובקיה", "en": "Slovakia"},
    "142": {"he": "סמואה", "en": "Samoa"},
    "143": {"he": "סן מרינו", "en": "San Marino"},
    "144": {"he": "סנגל", "en": "Senegal"},
    "145": {"he": "סנט וינסנט והגרנדינס", "en": "Saint Vincent and the Grenadines"},
    "146": {"he": "סנט לוסיה", "en": "Saint Lucia"},
    "147": {"he": "סנט קיטס ונוויס", "en": "Saint Kitts and Nevis"},
    "148": {"he": "ספרד", "en": "Spain"},
    "149": {"he": "סרביה", "en": "Serbia"},
    "150": {"he": "סרי לנקה", "en": "Sri Lanka"},
    "151": {"he": "עומאן", "en": "Oman"},
    "152": {"he": "עיראק", "en": "Iraq"},
    "153": {"he": "ערב הסעודית", "en": "Saudi Arabia"},
    "154": {"he": "פאלאו", "en": "Palau"},
    "155": {"he": "פולין", "en": "Poland"},
    "156": {"he": "פורטוגל", "en": "Portugal"},
    "157": {"he": "פיג'י", "en": "Fiji"},
    "158": {"he": "פיליפינים", "en": "Philippines"},
    "159": {"he": "פינלנד", "en": "Finland"},
    "160": {"he": "פנמה", "en": "Panama"},
    "161": {"he": "פפואה ניו גיני", "en": "Papua New Guinea"},
    "162": {"he": "פקיסטאן", "en": "Pakistan"},
    "163": {"he": "פרגוואי", "en": "Paraguay"},
    "164": {"he": "פרו", "en": "Peru"},
    "165": {"he": "צפון מקדוניה", "en": "North Macedonia"},
    "166": {"he": "צ'אד", "en": "Chad"},
    "167": {"he": "צ'ילה", "en": "Chile"},
    "168": {"he": "צ'כיה", "en": "Czechia"},
    "169": {"he": "צרפת", "en": "France"},
    "170": {"he": "צ'צניה (רוסיה)", "en": "Chechnya (Russia)"},
    "171": {"he": "קובה", "en": "Cuba"},
    "172": {"he": "קולומביה", "en": "Colombia"},
    "173": {"he": "קוסובו", "en": "Kosovo"},
    "174": {"he": "קוסטה ריקה", "en": "Costa Rica"},
    "175": {"he": "קומורוס (איי קומרוס)", "en": "Comoros"},
    "176": {"he": "קונגו (הרפובליקה הדמוקרטית)", "en": "Democratic Republic of the Congo"},
    "177": {"he": "קוריאה הדרומית", "en": "South Korea"},
    "178": {"he": "קוריאה הצפונית", "en": "North Korea"},
    "179": {"he": "קזחסטן", "en": "Kazakhstan"},
    "180": {"he": "קטאר", "en": "Qatar"},
    "181": {"he": "קייפ ורדה", "en": "Cape Verde"},
    "182": {"he": "קירגיזסטן", "en": "Kyrgyzstan"},
    "183": {"he": "קיריבטי", "en": "Kiribati"},
    "184": {"he": "קמבודיה", "en": "Cambodia"},
    "185": {"he": "קמרון", "en": "Cameroon"},
    "186": {"he": "קנדה", "en": "Canada"},
    "187": {"he": "קניה", "en": "Kenya"},
    "188": {"he": "קפריסין", "en": "Cyprus"},
    "189": {"he": "קרואטיה", "en": "Croatia"},
    "190": {"he": "רואנדה", "en": "Rwanda"},
    "191": {"he": "רומניה", "en": "Romania"},
    "192": {"he": "רוסיה", "en": "Russia"},
    "193": {"he": "שוודיה", "en": "Sweden"},
    "194": {"he": "שווייץ", "en": "Switzerland"},
    "195": {"he": "תאילנד", "en": "Thailand"},
    "196": {"he": "תוניסיה", "en": "Tunisia"},
    "197": {"he": "תורכיה", "en": "Turkey"},
    "198": {"he": "תורכמניסטן", "en": "Turkmenistan"},
    "199": {"he": "תימן", "en": "Yemen"}
}

# Keys are the 'Data.pic.Name' from the API
# Values are lists of warning levels
GOV_API_DATA_PIC_NAME_TO_ISO = {
    "איום בינוני.png": [3],
    "איום גבוה.png": [4],
    "איום מזדמן.png": [2],
    "ללא אזהרה.png": [1],
    "רמה 1 ו2.png": [1, 2],
    "רמה 1 ו3.png": [1, 3],
    "רמה 2 ו3.png": [2, 3],
    "רמה 2 ו4.png": [2, 4],
    "רמה 3 ו4.png": [3, 4],
}

# Keys are the 'UrlName' from the API
# Values are standard ISO Alpha-3 codes
GOV_API_URLNAME_TO_ISO = {
    "1united-arab-emirates": "ARE",
    "eritreans": "ERI",
    "bosnia-and-herzegovina": "BIH",
    "brunei": "BRN",
    "1south_africa": "ZAF",
    "maldives": "MDV",
    "ivory-coast": "CIV",
    "1morocco": "MAR",
    "niger": "NER",
    "sierra-leone": "SLE",
    "1senegal": "SEN",
    "arab-saudi": "SAU",
    "chad": "TCD",
    "kazakhstan": "KAZ",
    "kyrgyzstan": "KGZ",
    "1turkmenistan": "TKM",
    "iran1": "IRN",
    "algeria": "DZA",
    "afghanistan": "AFG",
    "burkina-faso": "BFA",
    "1bahrain": "BHR",
    "bangladesh": "BGD",
    "central-african-republic": "CAF",
    "jordan": "JOR",
    "kuwait": "KWT",
    "1lebanon": "LBN",
    "libya": "LBY",
    "mauritania": "MRT",
    "1mali": "MLI",
    "malaysia": "MYS",
    "1egypt": "EGY",
    "1sudan": "SDN",
    "1somalia": "SOM",
    "syria": "SYR",
    "sinai_peninsula": "EGY",  # Mapped to Egypt parent
    "oman": "OMN",
    "iraq": "IRQ",
    "pakistan": "PAK",
    "chechnya": "RUS",  # Mapped to Russia parent
    "1north-korea": "PRK",
    "qatar": "QAT",
    "tunisia": "TUN",
    "1turkey": "TUR",
    "yaman": "YEM",
    "uganda": "UGA",
    "1austria": "AUT",
    "1australia": "AUS",
    "1ukraine": "UKR",
    "azerbaijan": "AZE",
    "italy1": "ITA",
    "ireland": "IRL",
    "1angola": "AGO",
    "armenia": "ARM",
    "botswana": "BWA",
    "burundi": "BDI",
    "belgium": "BEL",
    "britain": "GBR",
    "gabon": "GAB",
    "georgia": "GEO",
    "ghana": "GHA",
    "guinea": "GIN",
    "equatorial-guinea": "GNQ",
    "guinea-bissau": "GNB",
    "gambia": "GMB",
    "1germany": "DEU",
    "denmark": "DNK",
    "1south_sudan": "SSD",
    "1netherlands": "NLD",
    "republic_congo": "COG",  # Congo-Brazzaville
    "zimbabwe": "ZWE",
    "zambia": "ZMB",
    "tanzania": "TZA",
    "1greece": "GRC",
    "1liberia": "LBR",
    "lesotho": "LSO",
    "mauritius": "MUS",
    "madagascar": "MDG",
    "1malawi": "MWI",
    "malta": "MLT",
    "namibia": "NAM",
    "saint-thomas-and-prince": "STP",
    "eswatini": "SWZ",
    "1spain": "ESP",
    "sri-lanka": "LKA",
    "1france": "FRA",
    "1colombia": "COL",
    "comoros": "COM",
    "cape-verde": "CPV",
    "1canada": "CAN",
    "rwanda": "RWA",
    "1sweden": "SWE",
    "uruguay": "URY",
    "the-bahamas": "BHS",
    "marshall-islands": "MHL",
    "seychelles": "SYC",
    "solomon-islands": "SLB",
    "iceland": "ISL",
    "el-salvador": "SLV",
    "abania": "ALB",
    "andorra": "AND",
    "antigua-and-barbuda": "ATG",
    "estoniya": "EST",
    "ecuador": "ECU",
    "argentina": "ARG",
    "1usa": "USA",
    "bhutan": "BTN",
    "bulgaria": "BGR",
    "bolivia": "BOL",
    "belarus": "BLR",
    "belize": "BLZ",
    "barbados": "BRB",
    "guatemala": "GTM",
    "guyana": "GUY",
    "jamaica": "JAM",
    "grenada": "GRD",
    "dominica": "DMA",
    "haiti": "HTI",
    "hong-kong": "HKG",
    "hungary": "HUN",
    "honduras": "HND",
    "dominican-republic": "DOM",
    "1vietnam": "VNM",
    "vatican": "VAT",
    "vanuatu": "VUT",
    "tuvalu": "TUV",
    "1tonga": "TON",
    "1taiwan": "TWN",
    "trinidad-and-tobago": "TTO",
    "1japan": "JPN",
    "laos": "LAO",
    "luxembourg": "LUX",
    "latvia": "LVA",
    "lithuania": "LTU",
    "liechtenstein": "LIE",
    "moldova": "MDA",
    "mongolia": "MNG",
    "1montenegro": "MNE",
    "monaco": "MCO",
    "east_timor": "TLS",
    "1myanmar": "MMR",
    "micronesia": "FSM",
    "1mexico": "MEX",
    "nauru": "NRU",
    "norway": "NOR",
    "new-zealand": "NZL",
    "nicaragua": "NIC",
    "nepal": "NPL",
    "suriname": "SUR",
    "china": "CHN",
    "1singapore": "SGP",
    "slovenia": "SVN",
    "slovakia": "SVK",
    "samoa": "WSM",
    "san-marino": "SMR",
    "saint-vincent-and-the-grenadines": "VCT",
    "saint-lucia": "LCA",
    "saint-kitts-and-nevis": "KNA",
    "serbia": "SRB",
    "palau": "PLW",
    "1poland": "POL",
    "portugal": "PRT",
    "fiji": "FJI",
    "finland": "FIN",
    "panama": "PAN",
    "papua-new-guinea": "PNG",
    "paraguay": "PRY",
    "north-macedonia": "MKD",
    "1chile": "CHL",
    "czech": "CZE",
    "cuba": "CUB",
    "cosova": "XKX",  # Common temporary code for Kosovo
    "costa-rica": "CRI",
    "1south-korea": "KOR",
    "kiribati": "KIR",
    "cambodia": "KHM",
    "cyprus": "CYP",
    "croatia": "HRV",
    "1romania": "ROU",
    "1switzerland": "CHE",
    "1ethiopia": "ETH",
    "1brazil": "BRA",
    "1peru": "PER",
    "1kenya": "KEN",
    "benin": "BEN",
    "djibouti": "DJI",
    "0india": "IND",
    "venezuela": "VEN",
    "togo": "TGO",
    "mozambique": "MOZ",
    "1nigeria": "NGA",
    "1philippines": "PHL",
    "1congo": "COD",  # DR Congo
    "cameroun": "CMR",
    "1russia": "RUS",
    "1thailand": "THA",
    "uzbekistan": "UZB",
    "indonesia": "IDN",
    "tajikistan": "TJK"
}
