# Keys are the 'Data.pic.Name' from the API
# Values are lists of warning levels
GOV_API_DATA_PIC_NAME_TO_ISO = {
    "איום בינוני.png": [3],
    "איום גבוה.png": [4],
    "איום מזדמן.png": [2],
    "ללא אזהרה.png": [1],
    "רמה 1 ו2.png": [1, 2],
    "רמה 1 ו3.png": [1, 3],
    "רמה 2 ו3.png": [2, 3],
    "רמה 2 ו4.png": [2, 4],
    "רמה 3 ו4.png": [3, 4],
}

# Keys are the 'UrlName' from the API
# Values are standard ISO Alpha-3 codes
GOV_API_URLNAME_TO_ISO = {
    "1united-arab-emirates": "ARE",
    "eritreans": "ERI",
    "bosnia-and-herzegovina": "BIH",
    "brunei": "BRN",
    "1south_africa": "ZAF",
    "maldives": "MDV",
    "ivory-coast": "CIV",
    "1morocco": "MAR",
    "niger": "NER",
    "sierra-leone": "SLE",
    "1senegal": "SEN",
    "arab-saudi": "SAU",
    "chad": "TCD",
    "kazakhstan": "KAZ",
    "kyrgyzstan": "KGZ",
    "1turkmenistan": "TKM",
    "iran1": "IRN",
    "algeria": "DZA",
    "afghanistan": "AFG",
    "burkina-faso": "BFA",
    "1bahrain": "BHR",
    "bangladesh": "BGD",
    "central-african-republic": "CAF",
    "jordan": "JOR",
    "kuwait": "KWT",
    "1lebanon": "LBN",
    "libya": "LBY",
    "mauritania": "MRT",
    "1mali": "MLI",
    "malaysia": "MYS",
    "1egypt": "EGY",
    "1sudan": "SDN",
    "1somalia": "SOM",
    "syria": "SYR",
    "sinai_peninsula": "EGY",  # Mapped to Egypt parent
    "oman": "OMN",
    "iraq": "IRQ",
    "pakistan": "PAK",
    "chechnya": "RUS",  # Mapped to Russia parent
    "1north-korea": "PRK",
    "qatar": "QAT",
    "tunisia": "TUN",
    "1turkey": "TUR",
    "yaman": "YEM",
    "uganda": "UGA",
    "1austria": "AUT",
    "1australia": "AUS",
    "1ukraine": "UKR",
    "azerbaijan": "AZE",
    "italy1": "ITA",
    "ireland": "IRL",
    "1angola": "AGO",
    "armenia": "ARM",
    "botswana": "BWA",
    "burundi": "BDI",
    "belgium": "BEL",
    "britain": "GBR",
    "gabon": "GAB",
    "georgia": "GEO",
    "ghana": "GHA",
    "guinea": "GIN",
    "equatorial-guinea": "GNQ",
    "guinea-bissau": "GNB",
    "gambia": "GMB",
    "1germany": "DEU",
    "denmark": "DNK",
    "1south_sudan": "SSD",
    "1netherlands": "NLD",
    "republic_congo": "COG",  # Congo-Brazzaville
    "zimbabwe": "ZWE",
    "zambia": "ZMB",
    "tanzania": "TZA",
    "1greece": "GRC",
    "1liberia": "LBR",
    "lesotho": "LSO",
    "mauritius": "MUS",
    "madagascar": "MDG",
    "1malawi": "MWI",
    "malta": "MLT",
    "namibia": "NAM",
    "saint-thomas-and-prince": "STP",
    "eswatini": "SWZ",
    "1spain": "ESP",
    "sri-lanka": "LKA",
    "1france": "FRA",
    "1colombia": "COL",
    "comoros": "COM",
    "cape-verde": "CPV",
    "1canada": "CAN",
    "rwanda": "RWA",
    "1sweden": "SWE",
    "uruguay": "URY",
    "the-bahamas": "BHS",
    "marshall-islands": "MHL",
    "seychelles": "SYC",
    "solomon-islands": "SLB",
    "iceland": "ISL",
    "el-salvador": "SLV",
    "abania": "ALB",
    "andorra": "AND",
    "antigua-and-barbuda": "ATG",
    "estoniya": "EST",
    "ecuador": "ECU",
    "argentina": "ARG",
    "1usa": "USA",
    "bhutan": "BTN",
    "bulgaria": "BGR",
    "bolivia": "BOL",
    "belarus": "BLR",
    "belize": "BLZ",
    "barbados": "BRB",
    "guatemala": "GTM",
    "guyana": "GUY",
    "jamaica": "JAM",
    "grenada": "GRD",
    "dominica": "DMA",
    "haiti": "HTI",
    "hong-kong": "HKG",
    "hungary": "HUN",
    "honduras": "HND",
    "dominican-republic": "DOM",
    "1vietnam": "VNM",
    "vatican": "VAT",
    "vanuatu": "VUT",
    "tuvalu": "TUV",
    "1tonga": "TON",
    "1taiwan": "TWN",
    "trinidad-and-tobago": "TTO",
    "1japan": "JPN",
    "laos": "LAO",
    "luxembourg": "LUX",
    "latvia": "LVA",
    "lithuania": "LTU",
    "liechtenstein": "LIE",
    "moldova": "MDA",
    "mongolia": "MNG",
    "1montenegro": "MNE",
    "monaco": "MCO",
    "east_timor": "TLS",
    "1myanmar": "MMR",
    "micronesia": "FSM",
    "1mexico": "MEX",
    "nauru": "NRU",
    "norway": "NOR",
    "new-zealand": "NZL",
    "nicaragua": "NIC",
    "nepal": "NPL",
    "suriname": "SUR",
    "china": "CHN",
    "1singapore": "SGP",
    "slovenia": "SVN",
    "slovakia": "SVK",
    "samoa": "WSM",
    "san-marino": "SMR",
    "saint-vincent-and-the-grenadines": "VCT",
    "saint-lucia": "LCA",
    "saint-kitts-and-nevis": "KNA",
    "serbia": "SRB",
    "palau": "PLW",
    "1poland": "POL",
    "portugal": "PRT",
    "fiji": "FJI",
    "finland": "FIN",
    "panama": "PAN",
    "papua-new-guinea": "PNG",
    "paraguay": "PRY",
    "north-macedonia": "MKD",
    "1chile": "CHL",
    "czech": "CZE",
    "cuba": "CUB",
    "cosova": "XKX",  # Common temporary code for Kosovo
    "costa-rica": "CRI",
    "1south-korea": "KOR",
    "kiribati": "KIR",
    "cambodia": "KHM",
    "cyprus": "CYP",
    "croatia": "HRV",
    "1romania": "ROU",
    "1switzerland": "CHE",
    "1ethiopia": "ETH",
    "1brazil": "BRA",
    "1peru": "PER",
    "1kenya": "KEN",
    "benin": "BEN",
    "djibouti": "DJI",
    "0india": "IND",
    "venezuela": "VEN",
    "togo": "TGO",
    "mozambique": "MOZ",
    "1nigeria": "NGA",
    "1philippines": "PHL",
    "1congo": "COD",  # DR Congo
    "cameroun": "CMR",
    "1russia": "RUS",
    "1thailand": "THA",
    "uzbekistan": "UZB",
    "indonesia": "IDN",
    "tajikistan": "TJK"
}
