# Keys are the 'Data.country' from the API
# Values are country name in Hebrew (from gov website html)
GOV_API_DATA_COUNTRY_TO_HEBREW_NAME = {
    "001": "אוגנדה",
    "002": "אוזבקיסטן",
    "003": "אוסטריה",
    "004": "אוסטרליה",
    "005": "אוקראינה",
    "006": "אורוגואי",
    "007": "אזרביג'אן",
    "008": "איחוד האמירויות הערביות",
    "009": "איטליה",
    "010": "איי בהאמה",
    "011": "איי מרשל",
    "012": "איי סיישל",
    "013": "איי שלמה",
    "014": "אינדונזיה",
    "015": "איסלנד",
    "016": "איראן",
    "017": "אירלנד",
    "018": "אל סלבדור",
    "019": "אלבניה",
    "020": "אלג'יריה",
    "021": "אנגולה",
    "022": "אנדורה",
    "023": "אנטיגואה וברבודה",
    "024": "אסטוניה",
    "025": "אפגניסטן",
    "026": "אקוואדור",
    "027": "ארגנטינה",
    "028": "אריתריאה",
    "029": "ארמניה",
    "030": "ארצות הברית",
    "031": "אתיופיה",
    "032": "בהוטן",
    "033": "בולגריה",
    "034": "בוליביה",
    "035": "בוסניה הרצגובינה",
    "036": "בוטסואנה",
    "037": "בורונדי",
    "038": "בורקינה פאסו",
    "039": "בחריין",
    "040": "בלארוס",
    "041": "בלגיה",
    "042": "בליז",
    "043": "בנגלדש",
    "044": "בנין",
    "045": "ברבדוס",
    "046": "ברוניי",
    "047": "ברזיל",
    "048": "בריטניה",
    "049": "גאבון",
    "050": "גאורגיה",
    "051": "גאנה",
    "052": "גווטמלה",
    "053": "גויאנה",
    "054": "ג'יבוטי",
    "055": "גינאה",
    "056": "גינאה המשוונית",
    "057": "גינאה-ביסאו",
    "058": "ג'מאיקה",
    "059": "גמביה",
    "060": "גרמניה",
    "061": "גרנדה",
    "062": "דומיניקה",
    "063": "דנמרק",
    "064": "דרום אפריקה",
    "065": "דרום סודאן",
    "066": "האיטי",
    "067": "האיים המלדיביים",
    "068": "הודו",
    "069": "הולנד",
    "070": "הונג קונג",
    "071": "הונגריה",
    "072": "הונדורס",
    "073": "הרפובליקה הדומיניקנית",
    "074": "הרפובליקה המרכז אפריקנית",
    "075": "הרפובליקה של קונגו ",
    "076": "וייטנאם",
    "077": "וותיקן",
    "078": "ונואטו",
    "079": "ונצואלה",
    "080": "זימבבואה",
    "081": "זמביה",
    "082": "חוף השנהב",
    "083": "טג'יקיסטאן",
    "084": "טובאלו",
    "085": "טוגו",
    "086": "טונגה",
    "087": "טייואן",
    "088": "טנזניה",
    "089": "טרינידד וטובגו",
    "090": "יוון",
    "091": "יפן",
    "092": "ירדן",
    "093": "כווית",
    "094": "לאוס",
    "095": "לבנון",
    "096": "לוב",
    "097": "לוקסמבורג",
    "098": "לטביה",
    "099": "ליבריה",
    "100": "ליטא",
    "101": "ליכטנשטיין",
    "102": "לסוטו",
    "103": "מאוריטניה",
    "104": "מאוריציוס",
    "105": "מאלי",
    "106": "מדגסקר",
    "107": "מוזמביק",
    "108": "מולדובה",
    "109": "מונגוליה",
    "110": "מונטנגרו",
    "111": "מונקו",
    "112": "מזרח טימור (הרפובליקה הדמוקרטית)",
    "113": "מיאנמר",
    "114": "מיקרונזיה",
    "115": "מלאווי",
    "116": "מלזיה",
    "117": "מלטה",
    "118": "מצרים",
    "119": "מקסיקו",
    "120": "מרוקו",
    "121": "נאורו",
    "123": "נורווגיה",
    "124": "ניגריה",
    "125": "ניו זילנד",
    "126": "ניז'ר",
    "127": "ניקרגואה",
    "128": "נמיביה",
    "129": "נפאל",
    "130": "סאו טומה ופרינסיפ",
    "131": "סודאן",
    "132": "סוואזילנד",
    "133": "סומליה",
    "134": "סוריה",
    "135": "סורינאם",
    "136": "סיירה ליאונה",
    "137": "סין",
    "138": "סינגפור",
    "139": "מצרים (חצי האי סיני)",
    "140": "סלובניה",
    "141": "סלובקיה",
    "142": "סמואה",
    "143": "סן מרינו",
    "144": "סנגל",
    "145": "סנט וינסנט והגרנדינס",
    "146": "סנט לוסיה",
    "147": "סנט קיטס ונוויס",
    "148": "ספרד",
    "149": "סרביה",
    "150": "סרי לנקה",
    "151": "עומאן",
    "152": "עיראק",
    "153": "ערב הסעודית",
    "154": "פאלאו",
    "155": "פולין",
    "156": "פורטוגל",
    "157": "פיג'י",
    "158": "פיליפינים",
    "159": "פינלנד",
    "160": "פנמה",
    "161": "פפואה ניו גיני",
    "162": "פקיסטאן",
    "163": "פרגוואי",
    "164": "פרו",
    "165": "צפון מקדוניה",
    "166": "צ'אד",
    "167": "צ'ילה",
    "168": "צ'כיה",
    "169": "צרפת",
    "170": "צ'צניה (רוסיה)",
    "171": "קובה",
    "172": "קולומביה",
    "173": "קוסובו",
    "174": "קוסטה ריקה",
    "175": "קומורוס (איי קומרוס)",
    "176": "קונגו (הרפובליקה הדמוקרטית)",
    "177": "קוריאה הדרומית",
    "178": "קוריאה הצפונית",
    "179": "קזחסטן",
    "180": "קטאר",
    "181": "קייפ ורדה",
    "182": "קירגיזסטן",
    "183": "קיריבטי",
    "184": "קמבודיה",
    "185": "קמרון",
    "186": "קנדה",
    "187": "קניה",
    "188": "קפריסין",
    "189": "קרואטיה",
    "190": "רואנדה",
    "191": "רומניה",
    "192": "רוסיה",
    "193": "שוודיה",
    "194": "שווייץ",
    "195": "תאילנד",
    "196": "תוניסיה",
    "197": "תורכיה",
    "198": "תורכמניסטן",
    "199": "תימן"
}

# Keys are the 'Data.pic.Name' from the API
# Values are lists of warning levels
GOV_API_DATA_PIC_NAME_TO_ISO = {
    "איום בינוני.png": [3],
    "איום גבוה.png": [4],
    "איום מזדמן.png": [2],
    "ללא אזהרה.png": [1],
    "רמה 1 ו2.png": [1, 2],
    "רמה 1 ו3.png": [1, 3],
    "רמה 2 ו3.png": [2, 3],
    "רמה 2 ו4.png": [2, 4],
    "רמה 3 ו4.png": [3, 4],
}

# Keys are the 'UrlName' from the API
# Values are standard ISO Alpha-3 codes
GOV_API_URLNAME_TO_ISO = {
    "1united-arab-emirates": "ARE",
    "eritreans": "ERI",
    "bosnia-and-herzegovina": "BIH",
    "brunei": "BRN",
    "1south_africa": "ZAF",
    "maldives": "MDV",
    "ivory-coast": "CIV",
    "1morocco": "MAR",
    "niger": "NER",
    "sierra-leone": "SLE",
    "1senegal": "SEN",
    "arab-saudi": "SAU",
    "chad": "TCD",
    "kazakhstan": "KAZ",
    "kyrgyzstan": "KGZ",
    "1turkmenistan": "TKM",
    "iran1": "IRN",
    "algeria": "DZA",
    "afghanistan": "AFG",
    "burkina-faso": "BFA",
    "1bahrain": "BHR",
    "bangladesh": "BGD",
    "central-african-republic": "CAF",
    "jordan": "JOR",
    "kuwait": "KWT",
    "1lebanon": "LBN",
    "libya": "LBY",
    "mauritania": "MRT",
    "1mali": "MLI",
    "malaysia": "MYS",
    "1egypt": "EGY",
    "1sudan": "SDN",
    "1somalia": "SOM",
    "syria": "SYR",
    "sinai_peninsula": "EGY",  # Mapped to Egypt parent
    "oman": "OMN",
    "iraq": "IRQ",
    "pakistan": "PAK",
    "chechnya": "RUS",  # Mapped to Russia parent
    "1north-korea": "PRK",
    "qatar": "QAT",
    "tunisia": "TUN",
    "1turkey": "TUR",
    "yaman": "YEM",
    "uganda": "UGA",
    "1austria": "AUT",
    "1australia": "AUS",
    "1ukraine": "UKR",
    "azerbaijan": "AZE",
    "italy1": "ITA",
    "ireland": "IRL",
    "1angola": "AGO",
    "armenia": "ARM",
    "botswana": "BWA",
    "burundi": "BDI",
    "belgium": "BEL",
    "britain": "GBR",
    "gabon": "GAB",
    "georgia": "GEO",
    "ghana": "GHA",
    "guinea": "GIN",
    "equatorial-guinea": "GNQ",
    "guinea-bissau": "GNB",
    "gambia": "GMB",
    "1germany": "DEU",
    "denmark": "DNK",
    "1south_sudan": "SSD",
    "1netherlands": "NLD",
    "republic_congo": "COG",  # Congo-Brazzaville
    "zimbabwe": "ZWE",
    "zambia": "ZMB",
    "tanzania": "TZA",
    "1greece": "GRC",
    "1liberia": "LBR",
    "lesotho": "LSO",
    "mauritius": "MUS",
    "madagascar": "MDG",
    "1malawi": "MWI",
    "malta": "MLT",
    "namibia": "NAM",
    "saint-thomas-and-prince": "STP",
    "eswatini": "SWZ",
    "1spain": "ESP",
    "sri-lanka": "LKA",
    "1france": "FRA",
    "1colombia": "COL",
    "comoros": "COM",
    "cape-verde": "CPV",
    "1canada": "CAN",
    "rwanda": "RWA",
    "1sweden": "SWE",
    "uruguay": "URY",
    "the-bahamas": "BHS",
    "marshall-islands": "MHL",
    "seychelles": "SYC",
    "solomon-islands": "SLB",
    "iceland": "ISL",
    "el-salvador": "SLV",
    "abania": "ALB",
    "andorra": "AND",
    "antigua-and-barbuda": "ATG",
    "estoniya": "EST",
    "ecuador": "ECU",
    "argentina": "ARG",
    "1usa": "USA",
    "bhutan": "BTN",
    "bulgaria": "BGR",
    "bolivia": "BOL",
    "belarus": "BLR",
    "belize": "BLZ",
    "barbados": "BRB",
    "guatemala": "GTM",
    "guyana": "GUY",
    "jamaica": "JAM",
    "grenada": "GRD",
    "dominica": "DMA",
    "haiti": "HTI",
    "hong-kong": "HKG",
    "hungary": "HUN",
    "honduras": "HND",
    "dominican-republic": "DOM",
    "1vietnam": "VNM",
    "vatican": "VAT",
    "vanuatu": "VUT",
    "tuvalu": "TUV",
    "1tonga": "TON",
    "1taiwan": "TWN",
    "trinidad-and-tobago": "TTO",
    "1japan": "JPN",
    "laos": "LAO",
    "luxembourg": "LUX",
    "latvia": "LVA",
    "lithuania": "LTU",
    "liechtenstein": "LIE",
    "moldova": "MDA",
    "mongolia": "MNG",
    "1montenegro": "MNE",
    "monaco": "MCO",
    "east_timor": "TLS",
    "1myanmar": "MMR",
    "micronesia": "FSM",
    "1mexico": "MEX",
    "nauru": "NRU",
    "norway": "NOR",
    "new-zealand": "NZL",
    "nicaragua": "NIC",
    "nepal": "NPL",
    "suriname": "SUR",
    "china": "CHN",
    "1singapore": "SGP",
    "slovenia": "SVN",
    "slovakia": "SVK",
    "samoa": "WSM",
    "san-marino": "SMR",
    "saint-vincent-and-the-grenadines": "VCT",
    "saint-lucia": "LCA",
    "saint-kitts-and-nevis": "KNA",
    "serbia": "SRB",
    "palau": "PLW",
    "1poland": "POL",
    "portugal": "PRT",
    "fiji": "FJI",
    "finland": "FIN",
    "panama": "PAN",
    "papua-new-guinea": "PNG",
    "paraguay": "PRY",
    "north-macedonia": "MKD",
    "1chile": "CHL",
    "czech": "CZE",
    "cuba": "CUB",
    "cosova": "XKX",  # Common temporary code for Kosovo
    "costa-rica": "CRI",
    "1south-korea": "KOR",
    "kiribati": "KIR",
    "cambodia": "KHM",
    "cyprus": "CYP",
    "croatia": "HRV",
    "1romania": "ROU",
    "1switzerland": "CHE",
    "1ethiopia": "ETH",
    "1brazil": "BRA",
    "1peru": "PER",
    "1kenya": "KEN",
    "benin": "BEN",
    "djibouti": "DJI",
    "0india": "IND",
    "venezuela": "VEN",
    "togo": "TGO",
    "mozambique": "MOZ",
    "1nigeria": "NGA",
    "1philippines": "PHL",
    "1congo": "COD",  # DR Congo
    "cameroun": "CMR",
    "1russia": "RUS",
    "1thailand": "THA",
    "uzbekistan": "UZB",
    "indonesia": "IDN",
    "tajikistan": "TJK"
}
